import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "../globals.css"

import { ThemeProvider } from "@/providers/theme-provider"

import { cn } from "@/lib/utils"
import Navbar from "@/components/Navbar/navbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(inter.className, "px-10")}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Navbar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}
